[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Nautilus = "ðŸ“˜"
wezterm = "ï„ "
# smile emoji
MyNiceProgram = "ðŸ˜›"

# Sway only
[aliases.app_id]
"^firefox$" = "firefox"
"^org.wezfurlong.wezterm$" = "wezterm"

# Both i3 and sway
[aliases.name]

[general]
separator = " î‚± "
split_at = ":"
empty_label = "ðŸŒ•"
display_property = "name" # class, instance, name
default_icon = "ï„‘"

[options]
remove_duplicates = true
no_names = true
no_icon_names = false
focus_fix = false
